name: Publish GitHub_Page

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - run: dotnet run -- deploy
      env:
        PAGE_TOKEN: ${{ secrets.PAGE_TOKEN }}
